version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: 'mongodb'
    volumes:
      - /tmp/saga:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
    restart: always

  borker:
    image: rabbitmq:3.13-rc-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_USER=saga-pattern-user
      - RABBITMQ_PASSWORD=saga-pattern-password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
